version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'dependencies'
  - package-ecosystem: 'npm'
    directory: 'server'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'dependencies'
  - package-ecosystem: 'npm'
    directory: 'client'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'dependencies'

